(in-package :bld-gen)

(defparameter *ops*
  '((+ n)
    (- n t)
    (/ n t)
    (* n)
    (expt 2)
    (abs 1)
    (sin 1)
    (cos 1)
    (tan 1)
    (asin 1)
    (acos 1)
    (atan 2 t)
    (sinh 1)
    (cosh 1)
    (tanh 1)
    (asinh 1)
    (acosh 1)
    (atanh 1)
    (log 2 t)
    (exp 1)
    (sqrt 1)
    (max n t)
    (min n t)
    (signum 1))
  "List of arithmetic function definitions. Form is: (FUNCTION NUMBER-OF-ARGS OPTIONAL-SECOND-ARG)")
